# Generated by Django 5.2.13 on 2026-04-20 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auditlog_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionorder',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revenue_sessions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_standalone', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orders_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('standalone_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active_sessions_at_close', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='api.branch')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
