# Generated by Django 5.2.13 on 2026-05-22 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sessionorder_unit_cost_dailyreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='session',
            name='branch',
        ),
        migrations.AlterModelOptions(
            name='featureflag',
            options={'ordering': ['key']},
        ),
        migrations.AlterModelOptions(
            name='inventorycategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['category__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='resourceunit',
            options={'ordering': ['code']},
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='featureflag',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='resourceunit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='resourceunit',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_start_session', models.BooleanField(default=False)),
                ('can_pause_session', models.BooleanField(default=False)),
                ('can_resume_session', models.BooleanField(default=False)),
                ('can_end_session', models.BooleanField(default=False)),
                ('can_add_session_order', models.BooleanField(default=False)),
                ('can_remove_session_order', models.BooleanField(default=False)),
                ('can_create_standalone_sale', models.BooleanField(default=False)),
                ('can_apply_discount', models.BooleanField(default=False)),
                ('can_view_shift_report', models.BooleanField(default=False)),
                ('can_close_shift', models.BooleanField(default=False)),
                ('can_manage_inventory', models.BooleanField(default=False)),
                ('can_update_stock', models.BooleanField(default=False)),
                ('can_view_audit_logs', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='featureflag',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='inventorycategory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='resourceunit',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
