# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_normalize_legacy_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
