# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auditlog_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_currency_enabled", models.BooleanField(default=False)),
                ("local_currency_code", models.CharField(blank=True, default="", max_length=3)),
                ("local_currency_name", models.CharField(blank=True, default="", max_length=50)),
                (
                    "local_units_per_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currency settings",
                "verbose_name_plural": "Currency settings",
            },
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="original_cost_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="original_cost_currency",
            field=models.CharField(blank=True, default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="original_price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="original_price_currency",
            field=models.CharField(blank=True, default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="session",
            name="original_payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="original_payment_currency",
            field=models.CharField(blank=True, default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="session",
            name="prepaid_amount_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
