# Generated by Codex on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_currency_settings_and_original_amounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="minimum_stock_level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="MonthlyExpenseSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("electricity", models.BooleanField(default=False)),
                ("internet", models.BooleanField(default=False)),
                ("rent", models.BooleanField(default=False)),
                ("salaries", models.BooleanField(default=False)),
                ("maintenance", models.BooleanField(default=False)),
                ("other", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Monthly expense settings",
                "verbose_name_plural": "Monthly expense settings",
            },
        ),
        migrations.CreateModel(
            name="MonthlyExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(unique=True)),
                (
                    "electricity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "internet",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("rent", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "salaries",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "maintenance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("other", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-month"],
            },
        ),
    ]
