# Generated by Codex on 2026-05-28

from django.db import migrations, models


def simplify_statuses(apps, schema_editor):
    ResourceUnit = apps.get_model("api", "ResourceUnit")
    ResourceUnit.objects.filter(status="AVAILABLE").update(status="ACTIVE")
    ResourceUnit.objects.filter(status__in=["MAINTENANCE", "DISABLED"]).update(
        status="STOPPED"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_monthly_expenses_and_min_stock"),
    ]

    operations = [
        migrations.RunPython(simplify_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="resourceunit",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Working"), ("STOPPED", "Stopped")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
